- README.md
- pcvalidate/pcvalidate.go
A one-line change to return a status code greater than 0 in case of validation errors
> The CLI tool returns 1 in case of errors

- keys.go
- parser_test.go
- tests/valid_dependsOn.yml
When submitting a publiccode which have multiple key for a given type it keeps and exports only the last one
#20
> Multiple array subkeys were not kept

- .circleci/config.yml
- pcvalidate/pcvalidate.go
- pcvalidate/pcvalidate_test.go
URL checker were not enforced and sometimes was validating absolute path as valid URL.
- Added some unit tests
- Recursively checks if there are nested tests in folders
Fixes:
#12 #17 #27
> Strictly checks if url is an url for real

- keys.go
> Fix segfault when remote-base-url is not a repo.

- pcvalidate/pcvalidate.go
> Fix crash when checking Azure Devops URL.

- keys.go
Improve the error message when checking whether the url key
in publiccode.yml and RemoteBaseURL are in the same repo.
> Improve the error message when checking url.

- errors.go
- parser.go
- parser_test.go
- tests/invalid_file_encoding.yml
core-0.2.2 (https://github.com/italia/publiccode.yml/pull/78)
defines UTF-8 as the only allowed encoding.
> Make sure the file encoding is UTF-8.

- keys.go
> clean unexpected keys error message

- .github/workflows/file-freshness.js
- .github/workflows/file-freshness.yml
Check for amministrazioni.txt freshness and open an issue if the
one from https://www.indicepa.gov.it is different than the local one.
Fix #82.
> chore: check for amministrazioni.txt freshness

- AUTHORS
> chore: add AUTHORS file

- .github/workflows/tests.yml
> chore: add linter to CI

- pcvalidate/pcvalidate.go
> fix: don't panic when the file argument doesn't exist

- .github/workflows/file-freshness.js
- README.md
> docs: remove go-bindata references, we don't use it anymore

- data/it/ipa_codes.txt
> chore: update it/ipa_codes.txt

- .github/workflows/file-freshness-pr.yml
> chore: open a PR when it/ipa_codes.txt changes

- README.md
> doc: update features in README.md

- data/oembed_providers.json
- fields.go
- parser_test.go
- validations.go
We don't need to keep OEmbed providers updated in real time, the static data file is more than enough.
Also, rename the function to isOEmbed().
> feat: remove network access in isOembed and update providers

- go.mod
- go.sum
See https://github.com/italia/httpclient-lib-go/pull/6.
> fix: infinite loop caused by httpclient-lib-go

- testdata/v0/invalid/description_en_gb_invalid_bcp47.yml.disabled
- testdata/v0/invalid/publiccodeYmlVersion_invalid.yml
- testdata/v0/valid/logo_with_url.yml
- testdata/v0/valid/maintenance_contacts_when_type_is_contract.yml
- testdata/v0/valid/maintenance_contacts_when_type_is_internal.yml
- testdata/v0/valid/valid.minimal.yml
- testdata/v0/valid/valid_spdx_or.yml
- testdata/v0/valid/valid_spdx_with.yml
- testdata/v0/valid/valid_with_major_version.yml
> test: use valid BCP47 tags in tests

- fields.go
- parser_test.go
> feat: add advice on what to do when finding deprecated fields
