keys.go, parser_test.go, tests/valid_maintenance_contacts_phone.yml
This PR aim to discuss how to treat phone fields, since they should be a `string` but as for `YAML` standard they could be ambiguous and treated as string/int/float64 in some cases.
Here casting if forced for the maintenance/contact/phone to string to avoid ambiguity.
Additionally: this bug is probably the root cause of many crawling failure during the night.
See here for details:
- https://github.com/nodeca/js-yaml/issues/394
- https://github.com/italia/publiccode-editor/issues/89
@alranel @libremente
=> phone fields may be ambiguous

.github/workflows/release.yml, .goreleaser.yml
Goreleaser is a great tool used by most of Go projects, it aims to manage all software releases. Attached there is a github action which will be triggered whenever a tag is set.
fix #34
=> Goreleaser to manage all software releases

.goreleaser.yml, README.md, pcvalidate/pcvalidate.go
Firing `pcvalidate` it was not possible to get what version you have locally. Now, thanks to goreleaser every release will be tagged and binaries, for different archs, will have those information built in.
Typing `pcvalidate -version` actual version will be printed out.
Fix: #33
=> pcvalidate cli add version command

pcvalidate/pcvalidate.go
In some environment such as Docker, containers, `runtime/debug` is not available and it was causing a nullpointer trying to get right version.
fix #37
=> fix nullpointer in container environment

check_generics.go, checks_test.go
Domain auth will be used only for domains in scope
fix: #26
=> Auth for domains in scope only

check_generics.go, checks_test.go, parser.go
Some code hosting platform have multiple domains, in order to use authentication we must check every possibile domain in scope.
=> Multiple domains support for token checks

parser.go, parser_test.go, tests/nil_categories.yml, tests/nil_name.yml
This will raise an error instead of brutal panic:
```
validation ko:
dependsOn/open: is empty. Remove it or fill with valid values
```
Fix: #43
=> raise an error when a key list is empty instead panicking

.goreleaser.yml
=> Ignoring darwin i386 arch in goreleaser

keys.go
Relax the check on the url key ignoring the protocol checking if
it matches with RemoteBaseURL.
This will make http://example.com/foo/bar and
https://example.com/foo/bar pass the test and be considered as
the same repo, which is pretty much always the case.
See developers-italia-backend#192
=> Ignore the protocol when checking the url key.

.github/workflows/release.yml
=> chore: use the DockerHub token instead of a password

.github/workflows/release.yml, .goreleaser.yml
* Explicitly pin goreleaser version so the release process doesn't
break when a new major of goreleaser gets out.
* Update .goreleaser.yml to reflect the current file format.
(https://goreleaser.com/deprecations/#dockerbinaries,
https://goreleaser.com/deprecations/#dockerbuilds)
=> chore: pin goreleaser version to v1.5.0 and update config

Dockerfile
Shrink down the final Docker image to 1/10th and use Go 1.16 for
building it.
=> chore: shrink the Docker image

.github/workflows/file-freshness.js
Add labels in diff, so that it's clearer which file is which and
in order to not update the issue with just the files' timestamps
if nothing changed in the diff.
=> chore: add labels to diff in file-freshness check

README.md
=> docs: remove CircleCI badge from README.md

parser_test.go, testdata/v0.2/invalid/localisation_availableLanguages_invalid_bcp47.yml.disabled
Go's language.Parse() is more lenient and allows non-BCP47 language
tags. Let's add a disabled test for now.
Related to #47.
=> test: add disabled test for BCP47 tag

.github/workflows/file-freshness.js
Fix bug introduced by f2ba6058a: go-bindata is supposed to be
only suggested in the issue message and not in the actual command.
=> fix: remove go-bindata from the file-freshness command

Dockerfile, Dockerfile.goreleaser
Fix goreleaser Dockerfile by moving the binary in the right directory
(within PATH) and make clear the purpose of the two Dockerfile in the
comments.
=> chore: fix goreleaser's Dockerfile

pcvalidate/pcvalidate.go
Remove the -export option from pcvalidate.
It didn't actually work since the introduction of -json
(1bfb94cbe4) and it's not terribly useful.
@sebbalex wdyt?
=> refactor: remove -export command line option from pcvalidate

go.mod, go.sum
Update to newly released v3.0.0 which fixes
https://github.com/go-yaml/yaml/issues/666.
=> chore: update go-yaml to v3.0.0

.github/workflows/file-freshness.js
Fix failure in running file-freshness.js
(https://github.com/octokit/octokit.js/issues/2450)
=> chore: esm.sh instead of skypack.dev

.github/workflows/file-freshness-pr.yml
Upgrade `peter-evans/create-pull-request` as GitHub changed their API and v6 is required to work properly.
See https://github.com/peter-evans/create-pull-request/issues/2790.
=> chore(deps): upgrade create-pull-request action

fields.go, parser_test.go, v0.go
The standard states that countryExtensionVersion must be "1.0". Keep "0.2" for retrocompatibility, as that wasn't a great idea to bump it. The change was made when the process was not refined yet.
countryExtensionVersion should and will be deprecated anyway.
=> fix: properly validate countryExtensionVersion

go.mod, parser.go, parser_test.go, validators/validator.go
Use go-validator's translations, which is its preferred way to customize error messages and allows us to make them more user friendly and extensible.
=> refactor: use go-validator's facility to customize messages

.github/workflows/release.yml, .goreleaser.yml
Bump goreleaser to 2.x and build packages for more archs, namely Darwin ARMv8.
See #201.
=> chore(ci): bump goreleaser and build more archs

.github/workflows/release.yml, .goreleaser.yml
Build multi-platform Docker image (https://goreleaser.com/cookbooks/multi-platform-docker-images/#creating-multi-platform-docker-images-with-goreleaser), with arm64.
Fix #201.
=> chore(ci): build multiplatform Docker image

parser_test.go, validators/common.go, validators/validator.go
Use the builtin validator and the nice alias feature of the validation library, and add a test for good measure.
=> refactor: use the alias feature for date validation

.golangci.yaml, internal/netutil.go, validators/validator.go
We should never panic in the library
=> fix: add os.Exit and log.Fatal.* to forbidigo

validations.go
Properly cleanup the downloaded file and its temp directory when running checks for image formats.
=> fix: properly cleanup temporary directory
